development:
  password: 19b3356d5852a869ed5e4048fd8e6d96
  theme_id: "100337582214"
  store: brothers-we-stand.myshopify.com
  ignore_files:
  - config/settings_data.json
  - "scripts/*"
  - "styles/*"
